### ISSUE TITLE
Tablas mutantes

### ISSUE THREAD

**Issue by agarciamontoro** [agarciamontoro/BDD_1415#14]
Modificar los disparadores hechos (¿compound trigger?) y tenerlo en cuenta para los que quedan por crear: hay que evitar el error de tablas mutantes :japanese_goblin:

**Comment by Darth-ATA** [comment]
Realizada la modificación, bastaba poner PRAGMA AUTONOMOUS_TRANSACTION en el DECLARE de los disparadores, y un COMMIT; entes de acabar el disparador.
