### ISSUE TITLE
Revisar atributos Ciudad y Provincia.

### ISSUE THREAD

**Issue by agarciamontoro** [agarciamontoro/BDD_1415#24]
1. Hacer un refactor general cambiando `Ciudad` por `Provincia`.
2. Añadir `Ciudad` a Hotel: esta tabla tiene los dos, pero el importante es `Provincia`.
3. Mirar qué hacer con Proveedor; sólo tiene un atributo, y en los datos de prueba aparece como `Ciudad`, pero si ese atributo se llama `Gamusino` tampoco pasaría nada. Por consistencia con los datos de prueba, podemos dejarlo como `Ciudad`.

**Comment by agarciamontoro** [comment]
Proveedor se ha quedado con `Provincia`

**Comment by Darth-ATA** [comment]
Hecho para los procedimientos
