### ISSUE TITLE
Pasar a LaTeX

### ISSUE THREAD

**Issue by agarciamontoro** [agarciamontoro/BDD_1415#4]
Estaría bien pasar toda la documentación a LaTeX, pero no es crítico. Propongo dejarlo para el último momento, sólo si tenemos tiempo.

**Comment by analca3** [comment]
Siempre podéis dejarlo en Markdown (o Rmarkdown si queréis más funcionalidad como ecuaciones, símbolos o subíndices) y usar pandoc!

**Comment by Darth-ATA** [comment]
Muchas gracias @analca3 pero @agarciamontoro tiene conocimiento de un programa que pasa markdown a LaTeX.

**Comment by analca3** [comment]
Seguro que habla de pandoc!

**Comment by Darth-ATA** [comment]
Pues seguro :+1:

**Comment by Darth-ATA** [comment]
Vamos a pasar el markdown a pdf mediante http://dillinger.io/#
